# Generated by Django 4.0.4 on 2022-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_counter',
            field=models.PositiveIntegerField(),
        ),
    ]
