version: '3.9'

services:
  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --host 0.0.0.0' # reload
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - REDIS_URL=redis://redis
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis
  
  db:
    image: postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379


volumes:
  redis_data:
  postgres_data: