version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://demo:password@database:5432/demo
    restart: unless-stopped
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
